function Other = importOtherTable(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   Other = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   Other = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Other = importfile('F2_Other.csv', 2, 38);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/10/29 12:21:06

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);
% join all comment columns
dataArray{1,4} = strcat(dataArray{1,4},{' '},dataArray{1,5},{' '},dataArray{1,6});

%% Create output variable
Other = table(dataArray{1:4}, 'VariableNames', {'datetime','x','y','Comment'});
Other = table2struct(Other);
Other = Other(~cellfun(@isnan,{Other.x})); % remove empty rows
Other = struct2table(Other);
%Other.Comment = %% try to remove empty spaces after comments
